services:
  backend:
    build:
      dockerfile: dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis
  frontend:
    build:
      dockerfile: web.dockerfile
    ports:
      - 3001:80
    depends_on:
      - backend
  redis:
    image: redis
